[package]
name = "command-utils"
version = "0.1.0"
authors = ["sutr-app"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1" }
chrono = { version = "0.4" }
envy = { version = "0.4" }
futures = { version = "0.3" }
once_cell = { version = "1" }
opentelemetry = { version = "0.21" }
opentelemetry_sdk = { version = "0.21", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.20", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.14", features = ["metrics"] }
opentelemetry-semantic-conventions = { version = "0.13" }
opentelemetry-stdout = { version = "0.2" }
opentelemetry-zipkin = { version = "0.19", features = [
    "reqwest-client",
], default-features = false }
pnet = { version = "0.34" }
rand = { version = "0.8" }
redis = { version = "0.24", features = [
    "tokio-comp",
    "r2d2",
    "ahash",
    "cluster-async",
] }
rs-snowflake = { version = "0.6" }
serde = { version = "1" }
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
    "process",
    "parking_lot",
] }
tracing = { version = "0.1" }
tracing-opentelemetry = { version = "0.22" }
tracing-subscriber = { version = "0.3", features = [
    "tracing-log",
    "env-filter",
    "json",
] }

[dev-dependencies]
itertools = { version = "0.12" }
